# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_protocol_pb2 as grpc__protocol__pb2


class CalculateSumStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/CalculateSum/Add',
        request_serializer=grpc__protocol__pb2.Numbers.SerializeToString,
        response_deserializer=grpc__protocol__pb2.Answer.FromString,
        )
    self.ImageWH = channel.unary_unary(
        '/CalculateSum/ImageWH',
        request_serializer=grpc__protocol__pb2.Image.SerializeToString,
        response_deserializer=grpc__protocol__pb2.Size.FromString,
        )


class CalculateSumServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ImageWH(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculateSumServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=grpc__protocol__pb2.Numbers.FromString,
          response_serializer=grpc__protocol__pb2.Answer.SerializeToString,
      ),
      'ImageWH': grpc.unary_unary_rpc_method_handler(
          servicer.ImageWH,
          request_deserializer=grpc__protocol__pb2.Image.FromString,
          response_serializer=grpc__protocol__pb2.Size.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CalculateSum', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
